area54:

    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 20

    
    

    base_to_second_joint_position_controller:
        type: position_controllers/JointPositionController
        joint: grip_joint


gazebo_ros_control/pid_gains:

        
     grip_joint: {p: 2.0, i: 0.0, d: 0.0}
